name: mota_scholarship_app
description: MoTA Unified Scholarship Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Networking
  dio: ^5.4.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Secure Storage / Preferences
  shared_preferences: ^2.2.3
  
  # Navigation
  go_router: ^12.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_logo.jpg"
  web:
    generate: true
    image_path: "assets/images/app_logo.jpg"
